# Generated by Django 3.2.7 on 2021-09-17 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='product_id',
            new_name='product',
        ),
    ]
