# Generated by Django 3.2.7 on 2021-09-20 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_orderitemmodel_ordermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItemModel',
        ),
        migrations.DeleteModel(
            name='OrderModel',
        ),
    ]
