# Generated by Django 3.2.7 on 2021-09-21 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productmodel_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='featured_image',
        ),
    ]
