# Generated by Django 3.2.7 on 2021-09-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_productmodel_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='featured_image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
