# Generated by Django 3.2.7 on 2021-09-21 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productmodel_featured_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideModel',
            fields=[
                ('slide_id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=255)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='products.productmodel')),
            ],
            options={
                'db_table': 'slides',
                'ordering': ('-slide_id',),
            },
        ),
    ]
