# Generated by Django 3.2.7 on 2021-09-21 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_slidemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slidemodel',
            old_name='product_id',
            new_name='product',
        ),
    ]
