# Generated by Django 3.2.7 on 2021-09-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_product_id_slidemodel_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
